# Generated by Django 5.2.4 on 2025-07-23 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField(max_length=2000)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)])),
                ('education_level', models.CharField(choices=[('EF', 'ENSINO FUNDAMENTAL'), ('EM', 'ENSINO MÉDIO'), ('ES', 'ENSINO SUPERIOR')], max_length=2)),
            ],
        ),
    ]
