# Generated by Django 5.2.4 on 2025-07-23 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField()),
                ('display_order', models.PositiveSmallIntegerField(choices=[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e')])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.question')),
            ],
        ),
    ]
