# Generated by Django 5.2.4 on 2025-07-23 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['question', 'display_order']},
        ),
    ]
