# Generated by Django 5.2.4 on 2025-07-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_useranswer_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answered_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
